Parameters:
  ExecutionRoleArn:
    Type: String
    AllowedPattern: ^arn:aws[a-z\-]*:iam::\d{12}:role/?[a-zA-Z_0-9+=,.@\-_/]+$
    Description: The SageMaker Studio execution role
    MinLength: 1
  PortfolioName:
    Type: String
    Default: SageMaker Organization Templates
    Description: The name of the portfolio
    MinLength: 1
  PortfolioOwner:
    Type: String
    Default: administrator
    Description: The owner of the portfolio
    MaxLength: 50
    MinLength: 1
  ProductVersion:
    Type: String
    Default: "1.0"
    Description: The product version to deploy
    MinLength: 1
Resources:
  Portfolio856A4190:
    Type: AWS::ServiceCatalog::Portfolio
    Properties:
      DisplayName:
        Ref: PortfolioName
      ProviderName:
        Ref: PortfolioOwner
      Description: Organization templates for Drift Detection pipeline
  PortfolioPortfolioProductAssociation0d79f0ac3bc7766D6CD6:
    Type: AWS::ServiceCatalog::PortfolioProductAssociation
    Properties:
      PortfolioId:
        Ref: Portfolio856A4190
      ProductId:
        Ref: Product896941B4
  Product896941B4:
    Type: AWS::ServiceCatalog::CloudFormationProduct
    Properties:
      Name: Amazon Sagemaker Drift Detection Pipeline
      Owner:
        Ref: PortfolioOwner
      ProvisioningArtifactParameters:
        - DisableTemplateValidation: false
          Info:
            LoadTemplateFromURL:
              Fn::Sub: https://s3.${AWS::Region}.${AWS::URLSuffix}/amazon-sagemaker-safe-deployment-pipeline/drift-pipeline/e44fbebc95581ce1ded723b90c98eed7bc64811566829221298271189e2587eb.json
          Name:
            Ref: ProductVersion
      Description: Amazon SageMaker Project for a build and deployment pipeline that triggers on drift or schedule
      Tags:
        - Key: sagemaker:studio-visibility
          Value: "true"
  ProductsUseRolePolicy7FB0EE21:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Resource:
              Fn::Join:
                - ""
                - - "arn:"
                  - Ref: AWS::Partition
                  - ":iam::"
                  - Ref: AWS::AccountId
                  - :role/service-role/AmazonSageMakerServiceCatalogProductsUseRole
          - Action:
              - application-autoscaling:DeregisterScalableTarget
              - application-autoscaling:DeleteScalingPolicy
              - application-autoscaling:DescribeScalingPolicies
              - application-autoscaling:PutScalingPolicy
              - application-autoscaling:RegisterScalableTarget
              - application-autoscaling:DescribeScalableTargets
              - iam:CreateServiceLinkedRole
              - cloudwatch:DeleteAlarms
              - cloudwatch:DescribeAlarms
              - cloudwatch:PutMetricAlarm
              - codepipeline:PutJobSuccessResult
              - codepipeline:PutJobFailureResult
            Effect: Allow
            Resource: "*"
          - Action:
              - codepipeline:EnableStageTransition
              - codepipeline:DisableStageTransition
            Effect: Allow
            Resource:
              Fn::Join:
                - ""
                - - "arn:aws:codepipeline:"
                  - Ref: AWS::Region
                  - ":"
                  - Ref: AWS::AccountId
                  - :sagemaker-*
          - Action:
              - events:EnableRule
              - events:DisableRule
            Effect: Allow
            Resource:
              Fn::Join:
                - ""
                - - "arn:aws:events:"
                  - Ref: AWS::Region
                  - ":"
                  - Ref: AWS::AccountId
                  - :rule/sagemaker-*
          - Action: iam:CreateServiceLinkedRole
            Condition:
              StringLike:
                iam:AWSServiceName: sagemaker.application-autoscaling.amazonaws.com
            Effect: Allow
            Resource:
              Fn::Join:
                - ""
                - - "arn:aws:iam::"
                  - Ref: AWS::AccountId
                  - :role/aws-service-role/sagemaker.application-autoscaling.amazonaws.com/AWSServiceRoleForApplicationAutoScaling_SageMakerEndpoint
        Version: "2012-10-17"
      PolicyName: ProductsUseRolePolicy7FB0EE21
      Roles:
        - AmazonSageMakerServiceCatalogProductsUseRole
  LaunchRolePolicyA9E2E5B1:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - s3:GetObject*
              - s3:GetBucket*
              - s3:List*
            Effect: Allow
            Resource:
              - Fn::Join:
                  - ""
                  - - "arn:"
                    - Ref: AWS::Partition
                    - :s3:::amazon-sagemaker-safe-deployment-pipeline
              - Fn::Join:
                  - ""
                  - - "arn:"
                    - Ref: AWS::Partition
                    - :s3:::amazon-sagemaker-safe-deployment-pipeline/*
          - Action:
              - ssm:DescribeParameters
              - ssm:GetParameters
              - ssm:GetParameter
              - ssm:GetParameterHistory
            Effect: Allow
            Resource:
              Fn::Join:
                - ""
                - - "arn:"
                  - Ref: AWS::Partition
                  - ":ssm:"
                  - Ref: AWS::Region
                  - ":"
                  - Ref: AWS::AccountId
                  - :parameter
                  - Ref: CodeCommitSeedBucket94EB6088
          - Action:
              - ssm:DescribeParameters
              - ssm:GetParameters
              - ssm:GetParameter
              - ssm:GetParameterHistory
            Effect: Allow
            Resource:
              Fn::Join:
                - ""
                - - "arn:"
                  - Ref: AWS::Partition
                  - ":ssm:"
                  - Ref: AWS::Region
                  - ":"
                  - Ref: AWS::AccountId
                  - :parameter
                  - Ref: CodeCommitBuildKey09FC7134
          - Action:
              - ssm:DescribeParameters
              - ssm:GetParameters
              - ssm:GetParameter
              - ssm:GetParameterHistory
            Effect: Allow
            Resource:
              Fn::Join:
                - ""
                - - "arn:"
                  - Ref: AWS::Partition
                  - ":ssm:"
                  - Ref: AWS::Region
                  - ":"
                  - Ref: AWS::AccountId
                  - :parameter
                  - Ref: CodeCommitDeployKey5E5A6E47
          - Action:
              - ssm:DescribeParameters
              - ssm:GetParameters
              - ssm:GetParameter
              - ssm:GetParameterHistory
            Effect: Allow
            Resource:
              Fn::Join:
                - ""
                - - "arn:"
                  - Ref: AWS::Partition
                  - ":ssm:"
                  - Ref: AWS::Region
                  - ":"
                  - Ref: AWS::AccountId
                  - :parameter
                  - Ref: LambdaKey984A39D9
        Version: "2012-10-17"
      PolicyName: LaunchRolePolicyA9E2E5B1
      Roles:
        - AmazonSageMakerServiceCatalogProductsLaunchRole
  PortfolioPrincipalAssociation:
    Type: AWS::ServiceCatalog::PortfolioPrincipalAssociation
    Properties:
      PortfolioId:
        Ref: Portfolio856A4190
      PrincipalARN:
        Ref: ExecutionRoleArn
      PrincipalType: IAM
    DependsOn:
      - Product896941B4
  LaunchRoleConstraint:
    Type: AWS::ServiceCatalog::LaunchRoleConstraint
    Properties:
      PortfolioId:
        Ref: Portfolio856A4190
      ProductId:
        Ref: Product896941B4
      Description:
        Fn::Join:
          - ""
          - - "Launch as arn:"
            - Ref: AWS::Partition
            - ":iam::"
            - Ref: AWS::AccountId
            - :role/service-role/AmazonSageMakerServiceCatalogProductsLaunchRole
      RoleArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":iam::"
            - Ref: AWS::AccountId
            - :role/service-role/AmazonSageMakerServiceCatalogProductsLaunchRole
    DependsOn:
      - PortfolioPrincipalAssociation
  CodeCommitSeedBucket94EB6088:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Value: amazon-sagemaker-safe-deployment-pipeline
      Name: /drift-pipeline/CodeCommitSeedBucket
  CodeCommitBuildKey09FC7134:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Value: drift-pipeline/be4dfed42e0626f2201f8ce29518fb4e31fb640eca88a156fedc5b8d568c6c1c.zip
      Name: /drift-pipeline/CodeCommitBuildKey
  CodeCommitDeployKey5E5A6E47:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Value: drift-pipeline/381262eab49cfaf013c17daf9216232c25761d7f0ec33583681b6b699adf4ecf.zip
      Name: /drift-pipeline/CodeCommitDeployKey
  LambdaKey984A39D9:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Value: drift-pipeline/794eca4997425c4bec9b267ede1318fbdd232a44a62bf0d083107fe9a6f270d5.zip
      Name: /drift-pipeline/LambdaKey
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAAE3WQwU7EMAxEv2XvaXar5cARthKnPVTlCyzX7Zq2MUoc0Krqv5O0SBQJTvEkk3kal7YsH+zp8ASfocB2OM4onuz8qoCDqTpXg4eJlLx5DoE03ffselOJC+ojqmkoSPRI2byfk6NlZXGLydlzIP/BSAgKo/R2rsVrJyPLSvlT1F7ahEhgQYacZapRYvsiflrlt2HF/fewS2OH/A7jr7zOXSE6vDUy0lYK2OliwrmAXDjYtXfS9hJxIL1AIMMw5QYj431j5Cl9ClNeXQL1P3vbL3FZFlPf9SbueLaPtjwd3gJz4aNTnsg22/kFLKE7OZUBAAA=
    Condition: CDKMetadataAvailable
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - af-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2

