Parameters:
  ExecutionRoleArn:
    Type: String
    AllowedPattern: ^arn:aws[a-z\-]*:iam::\d{12}:role/?[a-zA-Z_0-9+=,.@\-_/]+$
    Description: The SageMaker Studio execution role
    MinLength: 1
  PortfolioName:
    Type: String
    Default: SageMaker Organization Templates
    Description: The name of the portfolio
    MinLength: 1
  PortfolioOwner:
    Type: String
    Default: administrator
    Description: The owner of the portfolio
    MaxLength: 50
    MinLength: 1
  ProductVersion:
    Type: String
    Default: "1.0"
    Description: The product version to deploy
    MinLength: 1
  IAMusername:
    Type: String
    Default: sagemaker-github-actions-user
    Description: IAM user name to create for github actions
    MinLength: 1
Resources:
  GitHubLaunchRolePolicy1A27DA4F:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - secretsmanager:CreateSecret
              - secretsmanager:TagResource
            Effect: Allow
            Resource:
              Fn::Join:
                - ""
                - - "arn:aws:secretsmanager:"
                  - Ref: AWS::Region
                  - ":"
                  - Ref: AWS::AccountId
                  - :secret:sagemaker-*
        Version: "2012-10-17"
      PolicyName: GitHubLaunchRolePolicy1A27DA4F
      Roles:
        - AmazonSageMakerServiceCatalogProductsLaunchRole
  GitHubUser29F490A0:
    Type: AWS::IAM::User
    Properties:
      UserName:
        Ref: IAMusername
  GitHubUserDefaultPolicy4AD3F909:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - s3:CreateBucket
              - s3:GetBucket*
              - s3:ListAllMyBuckets
              - s3:ListBucket
              - s3:GetObject*
              - s3:PutObject*
            Effect: Allow
            Resource: arn:aws:s3:::sagemaker-*
          - Action:
              - sagemaker:Describe*
              - sagemaker:List*
              - sagemaker:Search
              - sagemaker:StartPipelineExecution
            Effect: Allow
            Resource: "*"
          - Action: lambda:*
            Effect: Allow
            Resource:
              Fn::Join:
                - ""
                - - "arn:aws:lambda:"
                  - Ref: AWS::Region
                  - ":"
                  - Ref: AWS::AccountId
                  - :function:sagemaker-*
          - Action: iam:PassRole
            Effect: Allow
            Resource:
              Fn::Join:
                - ""
                - - "arn:"
                  - Ref: AWS::Partition
                  - ":iam::"
                  - Ref: AWS::AccountId
                  - :role/service-role/AmazonSageMakerServiceCatalogProductsUseRole
        Version: "2012-10-17"
      PolicyName: GitHubUserDefaultPolicy4AD3F909
      Users:
        - Ref: GitHubUser29F490A0
  GitHubAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName:
        Ref: GitHubUser29F490A0
  GitHubAccessTokenAA3B9786:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name:
        Ref: IAMusername
      SecretString:
        Fn::Join:
          - ""
          - - '{"AccessKeyId": "'
            - Ref: GitHubAccessKey
            - '", "SecretAccessKey": "'
            - Fn::GetAtt:
                - GitHubAccessKey
                - SecretAccessKey
            - '"}'
  GitHubProductsUseRolePolicyBE60FCFC:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Resource:
              Fn::Join:
                - ""
                - - "arn:"
                  - Ref: AWS::Partition
                  - ":iam::"
                  - Ref: AWS::AccountId
                  - :role/service-role/AmazonSageMakerServiceCatalogProductsUseRole
          - Action:
              - application-autoscaling:DeregisterScalableTarget
              - application-autoscaling:DeleteScalingPolicy
              - application-autoscaling:DescribeScalingPolicies
              - application-autoscaling:PutScalingPolicy
              - application-autoscaling:RegisterScalableTarget
              - application-autoscaling:DescribeScalableTargets
              - cloudwatch:DeleteAlarms
              - cloudwatch:DescribeAlarms
              - cloudwatch:PutMetricAlarm
              - codepipeline:PutJobSuccessResult
              - codepipeline:PutJobFailureResult
            Effect: Allow
            Resource: "*"
          - Action: iam:CreateServiceLinkedRole
            Condition:
              StringLike:
                iam:AWSServiceName: sagemaker.application-autoscaling.amazonaws.com
            Effect: Allow
            Resource:
              Fn::Join:
                - ""
                - - "arn:aws:iam::"
                  - Ref: AWS::AccountId
                  - :role/aws-service-role/sagemaker.application-autoscaling.amazonaws.com/AWSServiceRoleForApplicationAutoScaling_SageMakerEndpoint
          - Action: lambda:*
            Effect: Allow
            Resource:
              Fn::Join:
                - ""
                - - "arn:aws:lambda:"
                  - Ref: AWS::Region
                  - ":"
                  - Ref: AWS::AccountId
                  - :function:sagemaker-*
        Version: "2012-10-17"
      PolicyName: GitHubProductsUseRolePolicyBE60FCFC
      Roles:
        - AmazonSageMakerServiceCatalogProductsUseRole
  Portfolio856A4190:
    Type: AWS::ServiceCatalog::Portfolio
    Properties:
      DisplayName:
        Ref: PortfolioName
      ProviderName:
        Ref: PortfolioOwner
      Description: Organization templates for github axtions pipeline
  PortfolioPortfolioProductAssociation10d964e261deBFC0FC72:
    Type: AWS::ServiceCatalog::PortfolioProductAssociation
    Properties:
      PortfolioId:
        Ref: Portfolio856A4190
      ProductId:
        Ref: Product896941B4
  Product896941B4:
    Type: AWS::ServiceCatalog::CloudFormationProduct
    Properties:
      Name: Amazon SageMaker drift detection template for github actions
      Owner:
        Ref: PortfolioOwner
      ProvisioningArtifactParameters:
        - DisableTemplateValidation: false
          Info:
            LoadTemplateFromURL:
              Fn::Sub: https://s3.${AWS::URLSuffix}/aws-ml-blog/artifacts/amazon-sagemaker-drift-detection/4b200e6e607c8f584759227932a334cfc21edc3c41d843185f0e32cf54f003cb.json
          Name:
            Ref: ProductVersion
      Description: This template requires a GitHub User and token which are stored in Amazon Secrets Manager for callback into GitHub Actions workflows for when a model is approved in the registry, or drift is deteted
      Tags:
        - Key: sagemaker:studio-visibility
          Value: "true"
  PortfolioPrincipalAssociation:
    Type: AWS::ServiceCatalog::PortfolioPrincipalAssociation
    Properties:
      PortfolioId:
        Ref: Portfolio856A4190
      PrincipalARN:
        Ref: ExecutionRoleArn
      PrincipalType: IAM
    DependsOn:
      - Product896941B4
  LaunchRoleConstraint:
    Type: AWS::ServiceCatalog::LaunchRoleConstraint
    Properties:
      PortfolioId:
        Ref: Portfolio856A4190
      ProductId:
        Ref: Product896941B4
      Description:
        Fn::Join:
          - ""
          - - "Launch as arn:"
            - Ref: AWS::Partition
            - ":iam::"
            - Ref: AWS::AccountId
            - :role/service-role/AmazonSageMakerServiceCatalogProductsLaunchRole
      RoleArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":iam::"
            - Ref: AWS::AccountId
            - :role/service-role/AmazonSageMakerServiceCatalogProductsLaunchRole
    DependsOn:
      - PortfolioPrincipalAssociation
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAAE3VQ0UoDQQz8lr5vtz0K4qNtwRcFj4ofEHLpNfZuUzZZpRz37+7eKVTQp2SSYWaSylfVnV8vHuBTl9icVwNKJD+8GuDZ7Y+hhgg9GUV3IJUUkcr0JdklmduqkmVqy6F1ewlqMaEVwi05Lxo2ljC64jIw9H6opWO8Tg5z96bZI8OfukUk1Se6jk4JI5n2EKClmMNNuJDmrjDiByMhGHTSFvVox6wrs8FfoI7S5LD5BEGGEs/tO0nNo8R+gt+E6YL/FjdqHJAv0P3SO4ZnSAFPB+lofg9wKHE3SyivUz99MGO/S3gm24HSOLr6aicJq42/99V68a7My5iCcU/+MNcvI8V+5LgBAAA=
    Condition: CDKMetadataAvailable
Outputs:
  SecretKey:
    Value:
      Ref: IAMusername
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - af-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2

