AWSTemplateFormatVersion: "2010-09-09"
Description: Setup IAM user for GitHub Actions and IAM role for SageMaker

Parameters:
  GitHubActionsUserName:
    Type: String
    Default: github-actions-cloudformation-sagemaker
  SageMakerExecutionRoleArn:
    Type: String
    Description: The sagemaker execution role to allow assuming from github actions 

Resources:
  GitHubActionsUser:
    Type: AWS::IAM::User
    Properties:
      UserName: !Ref GitHubActionsUserName

  GitHubActionsUserPolicy:
    Type: AWS::IAM::Policy
    Properties:
      Users:
        - !Ref GitHubActionsUser
      PolicyName: allow-github-actions-sagemaker
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action: "iam:AssumeRole"
            Effect: Allow
            Resource: !Ref SageMakerExecutionRoleArn

  GitHubActionsUserAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref GitHubActionsUser
      Serial: 1

  GitHubActionsCredentials:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Ref GitHubActionsUserName
      SecretString: !Sub |
        {
          "AccessKeyId":"${GitHubActionsUserAccessKey}",
          "SecretAccessKey":"${GitHubActionsUserAccessKey.SecretAccessKey}"
        }