# Model Building Pipeline

name: Build Model

on:
  push:
    branches:
      - split-workflow
  # pull_request:
  #   branches:
  #     - main
  # schedule:
  #   - cron: '0 12 1 * * *'
  workflow_dispatch:
  repository_dispatch:
    types: [build] # Does this need to make the job name?

env:
  AWS_REGION: us-east-1
  PROJECT_NAME: ${{ github.event.repository.name }}

jobs:
  build:
    name: Build Model
    runs-on: ubuntu-latest
    environment:
      name: development
    defaults:
      run:
        shell: bash
        working-directory: ./build_pipeline
    steps:
      # TEMP: output the payload to test dispatch event
      - name: Dump the client payload context
        if: ${{ github.event.client_payload != null }}
        run: echo "${{ toJson(github.event.client_payload) }}"

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "12"
          cache: npm

      - name: Install Requirements
        run: |
          npm install -g aws-cdk # Install cdk
          pip install --requirement requirements.txt

      - name: Configure AWS Credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          role-duration-seconds: 1200

      - name: Build Pipeline
        id: build-pipeline
        env:
          SAGEMAKER_PROJECT_NAME: ${{ env.PROJECT_NAME }}
          SAGEMAKER_PIPELINE_NAME: ${{ env.PROJECT_NAME }}-pipeline
          SAGEMAKER_PIPELINE_DESCRIPTION: "Drift detection model build pipeline created from GitHub actions"
          SAGEMAKER_PIPELINE_ROLE_ARN: arn:aws:iam::${{ steps.creds.outputs.aws-account-id }}:role/service-role/AmazonSageMakerServiceCatalogProductsUseRole
        run: |
          export SAGEMAKER_PROJECT_ID=`aws sagemaker describe-project --project-name $SAGEMAKER_PROJECT_NAME --query ProjectId --output text`
          echo "Project id: $SAGEMAKER_PROJECT_ID"
          export ARTIFACT_BUCKET=sagemaker-project-$SAGEMAKER_PROJECT_ID-$AWS_REGION
          echo "Artifact Bucket: $ARTIFACT_BUCKET"
          npx cdk synth --path-metadata false --asset-metadata=false > drift-pipeline.yml
          echo "::set-output name=pipeline_name::$SAGEMAKER_PIPELINE_NAME"

      - name: Print template
        run: cat drift-pipeline.yml

      - name: Create CFN Pipeline
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: sagemaker-${{ env.PROJECT_NAME }}-pipeline
          template: ./build_pipeline/drift-pipeline.yml # Need to specify working-directory
          role-arn: arn:aws:iam::${{ steps.creds.outputs.aws-account-id }}:role/service-role/AmazonSageMakerServiceCatalogProductsUseRole
          no-fail-on-empty-changeset: "1"

      - name: Start Pipeline
        run: aws sagemaker start-pipeline-execution --pipeline-name ${{ steps.build-pipeline.outputs.pipeline_name }} --pipeline-parameters Name=InputSource,Value=GitHubAction#${{ github.run_number }}

      - name: Upload template
        uses: actions/upload-artifact@v2
        with:
          name: drift-pipeline
          path: ./build_pipeline/drift-pipeline.yml
