# Create a unified Build and Deploy pipeline that uses approval gates
# Build Model –> Deploy to staging with approval –> Deploy to prod with approval.
# https://timheuer.com/blog/add-approval-workflow-to-github-actions/

name: Endpoint Deployment

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0' # Runs on midnight on sunday every week
  repository_dispatch:
    types: [deploy]

env:
  AWS_REGION: us-east-1
  PROJECT_NAME: ${{ github.event.repository.name }}

jobs:
  deploy_staging:
    name: Deploy to staging
    runs-on: ubuntu-latest
    environment:
      name: staging # Use different environment that optionally requires approval
    defaults:
      run:
        shell: bash
        working-directory: ./deployment_pipeline
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "12"
          cache: npm

      - name: Install Requirements
        run: |
          npm install -g aws-cdk # Install cdk
          pip install --requirement requirements.txt

      - name: Configure AWS Credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          role-duration-seconds: 1200

      - name: Build Templates
        id: build-templates
        env:
          SAGEMAKER_PROJECT_NAME: ${{ env.PROJECT_NAME }}
          SAGEMAKER_EXECUTION_ROLE_ARN: arn:aws:iam::${{ steps.creds.outputs.aws-account-id }}:role/service-role/AmazonSageMakerServiceCatalogProductsUseRole
        run: |
          export SAGEMAKER_PROJECT_ID=`aws sagemaker describe-project --project-name $SAGEMAKER_PROJECT_NAME --query ProjectId --output text`
          echo "Project id: $SAGEMAKER_PROJECT_ID"
          export ARTIFACT_BUCKET=sagemaker-project-$SAGEMAKER_PROJECT_ID-$AWS_REGION
          echo "Artifact Bucket: $ARTIFACT_BUCKET"
          npx cdk synth drift-deploy-staging --path-metadata false --asset-metadata=false > drift-deploy-staging.yml

      - name: Print template
        run: cat drift-deploy-staging.yml

      - name: Deploy Staging
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: sagemaker-${{ env.PROJECT_NAME }}-deploy-staging
          template: ./deployment_pipeline/drift-deploy-staging.yml # Need to specify working-directory
          role-arn: arn:aws:iam::${{ steps.creds.outputs.aws-account-id }}:role/service-role/AmazonSageMakerServiceCatalogProductsUseRole
          no-fail-on-empty-changeset: "1"

      - name: Upload template
        uses: actions/upload-artifact@v2
        with:
          name: drift-deploy-staging
          path: ./deployment_pipeline/drift-deploy-staging.yml

  deploy_prod:
    needs: deploy_staging
    name: Deploy to prod
    if: ${{ github.ref == 'refs/heads/main' }} # Filter to only run on main branch
    runs-on: ubuntu-latest
    environment:
      name: prod # Use different environment that requires approval
    defaults:
      run:
        shell: bash
        working-directory: ./deployment_pipeline
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "12"
          cache: npm

      - name: Install Requirements
        run: |
          npm install -g aws-cdk # Install cdk
          pip install --requirement requirements.txt

      - name: Configure AWS Credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          role-duration-seconds: 1200

      - name: Build Templates
        id: build-templates
        env:
          SAGEMAKER_PROJECT_NAME: ${{ env.PROJECT_NAME }}
          SAGEMAKER_EXECUTION_ROLE_ARN: arn:aws:iam::${{ steps.creds.outputs.aws-account-id }}:role/service-role/AmazonSageMakerServiceCatalogProductsUseRole
        run: |
          export SAGEMAKER_PROJECT_ID=`aws sagemaker describe-project --project-name $SAGEMAKER_PROJECT_NAME --query ProjectId --output text`
          echo "Project id: $SAGEMAKER_PROJECT_ID"
          export ARTIFACT_BUCKET=sagemaker-project-$SAGEMAKER_PROJECT_ID-$AWS_REGION
          echo "Artifact Bucket: $ARTIFACT_BUCKET"
          npx cdk synth drift-deploy-prod --path-metadata false --asset-metadata=false > drift-deploy-prod.yml

      - name: Print Template
        run: cat drift-deploy-prod.yml

      - name: Deploy Prod
        id: deploy-pipeline
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: sagemaker-${{ env.PROJECT_NAME }}-deploy-prod
          template: ./deployment_pipeline/drift-deploy-prod.yml # Need to specify working-directory
          role-arn: arn:aws:iam::${{ steps.creds.outputs.aws-account-id }}:role/service-role/AmazonSageMakerServiceCatalogProductsUseRole
          no-fail-on-empty-changeset: "1"

      - name: Upload template
        uses: actions/upload-artifact@v2
        with:
          name: drift-deploy-prod
          path: ./deployment_pipeline/drift-deploy-prod.yml